feat: jig play count functionality and updated backend/api readme
ji-devs/ji-cloud pull request #1356
Opened 2021-08-16 22:19 UTC by LeahWhalen

added jig play count table
added jig play count route
tested jig play count
updated readme for backend/api setup for testing

2021-08-17 18:06 UTC, rrcwang requested changes
looking solid so far!

2021-08-17 18:06 UTC, rrcwang commented on backend/api/README.md
>  ```
have a section here for steps to complete before submitting a PR?

2021-08-17 23:31 UTC, mehcode commented on backend/api/migrations/20210813221459_jig-play-count.sql
> +    jig_id uuid             not null references jig (id) on delete cascade,
`jig_id` should be a `primary key` here

2021-09-14 01:52 UTC, rrcwang commented on backend/api/src/http/endpoints/jig/player.rs
> +        .expect("invalid player session token");
Should create a new error type to explicitly handle a decoding failure

2021-09-14 01:52 UTC, rrcwang commented on backend/api/src/http/endpoints/jig/player.rs
> +    let session_id = token.get("sub").unwrap().as_str().unwrap();
Prefer to avoid using `unwrap()` and handle with error type

2021-09-14 01:52 UTC, rrcwang commented on backend/api/src/db/jig/player.rs
> +
If the session instance is successfully completed, we should remove the row from the database

2021-09-15 16:40 UTC, closed without merging